---
- name: Prep server for initial windows update
  hosts: all
  tasks:

    - name: stop windows service
      ansible.windows.win_service:
        name: wuauserv
        state: stopped

    - name: Remove directory structure
      ansible.windows.win_file:
        path: C:\Windows\SoftwareDistribution
        state: absent

    - name: enable windows service
      ansible.windows.win_service:
        name: wuauserv
        start_mode: auto
        state: started       

    - name: Check into WSUS
      ansible.windows.win_powershell:
        script: |
          wuauclt /detectnow 
          
    - name: Check into WSUS
      ansible.windows.win_powershell:
        script: |
          wuauclt /reportnow           

    - name: Check into WSUS
      ansible.windows.win_powershell:
        script: |
          $updateSession = new-object -com \"Microsoft.Update.Session\"; $updates=$updateSession.CreateupdateSearcher().Search($criteria).Updates