---
- name: MicroServices Manager Prizegen Up
  hosts: localhost
  tasks:

  - name: copy
    shell: cp -R /home/.microservices.manager /home/runner/

  - name: mm prizegen up command - {{site_name}} {{host_number}}
    shell: mm --env {{site_name}} --action prizegen-up --hosts {{host_number}} --dry-run false
    register: result

  - debug: var=result.stdout_lines