---
- name: Install all updates and reboot as many times as needed
  hosts: all
  tasks:
  - name: Install all updates and reboot as many times a needed
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
      reboot: yes
      reboot_timeout: 3600
